# [build]
# rustflags = ['--cfg=erase_components']

#[target.wasm32-unknown-unknown]
#rustflags = ['--cfg', 'getrandom_backend="js"']

[target.'cfg(target_family = "wasm")']
rustflags = ['--cfg=getrandom_backend="wasm_js"']
